#!/usr/bin/python3
# -*- coding: UTF-8 -*-

"""
  List all movies in a given directory and returns one at random
"""


path = '/mnt/ARCADIA/Videos/peliculas/'

import argparse

parser = argparse.ArgumentParser(description='Retrive an unseen movie')

help_msg = 'Retrieve all unseen movies'
parser.add_argument('-a',action='store_true', default=False, help=help_msg)

args = parser.parse_args()



from os import listdir
from os.path import isfile, join
from random import choice


onlyfiles = [ join(path,f) for f in listdir(path) if isfile(join(path,f)) ]

ignored = ['srt','nfo']

movies = []
for f in onlyfiles:
   ext = f.split('.')[-1]
   if ext not in ignored:
      movies.append(f)

unseen = [ m for m in movies if any(map(str.isupper, m.split('/')[-1])) ]

if args.a:
   for m in unseen:
      name = m.split('/')[-1].replace('_',' ').capitalize()
      print('.'.join(name.split('.')[:-1]))
else:
   m = choice(unseen)
   name = m.split('/')[-1].replace('_',' ').capitalize()
   print('.'.join(name.split('.')[:-1]))
   print('totem',m)
