#!/bin/sh

# http://elinux.org/RPi_HardwareHistory#INFO_Revision_History

REVISION="$(grep "Revision" /proc/cpuinfo | cut -f2 | cut -c3-)"

case "${REVISION}" in
  "0002")
    INFO="Raspberry Pi 1 Model B [256MB] / PCB v1.0 (2012 Q1 / Original)"
    ;;
  "0003")
    INFO="Raspberry Pi 1 Model B [256MB] / PCB v1.0 (2012 Q3 / Fuses mod + D14 removed [ECN0001])"
    ;;
  "0004")
    INFO="Raspberry Pi 1 Model B [256MB] / PCB v2.0 (2012 Q3 / Sony)"
    ;;
  "0005")
    INFO="Raspberry Pi 1 Model B [256MB] / PCB v2.0 (2012 Q4 / Qisda)"
    ;;
  "0006")
    INFO="Raspberry Pi 1 Model B [256MB] / PCB v2.0 (2012 Q4 / Egoman)"
    ;;
  "0007")
    INFO="Raspberry Pi 1 Model A [256MB] / PCB v2.0 (2013 Q1 / Egoman)"
    ;;
  "0008")
    INFO="Raspberry Pi 1 Model A [256MB] / PCB v2.0 (2013 Q1 / Sony)"
    ;;
  "0009")
    INFO="Raspberry Pi 1 Model A [256MB] / PCB v2.0 (2013 Q1 / Qisda)"
    ;;
  "000d")
    INFO="Raspberry Pi 1 Model A [512MB] / PCB v2.0 (2012 Q4 / Egoman)"
    ;;
  "000e")
    INFO="Raspberry Pi 1 Model B [512MB] / PCB v2.0 (2012 Q4 / Sony)"
    ;;
  "000f")
    INFO="Raspberry Pi 1 Model B [512MB] / PCB v2.0 (2012 Q4 / Qisda)"
    ;;
  "0010")
    INFO="Raspberry Pi 1 Model B+ [512MB] / PCB v1.0 (2014 Q3 / Sony)"
    ;;
  "0011")
    INFO="Compute Module [512MB] / PCB v1.0 (2014 Q2 / Sony)"
    ;;
  "0012")
    INFO="Raspberry Pi 1 Model A+ [256MB] / PCB v1.1 (2014 Q4 / Sony)"
    ;;
  "0013")
    INFO="Raspberry Pi 1 Model B+ [512MB] / PCB v1.2 (2015 Q1 / ????)"
    ;;
  "0014")
    INFO="Compute Module [512MB] / PCB v1.0 (2014 Q2 / Embest)"
    ;;
  "0015")
    INFO="Raspberry Pi 1 Model A+ [256/512MB] / PCB v1.1 (???? ?? / Embest)"
    ;;
  "a01040")
    INFO="Raspberry Pi 2 Model B [1GB] / PCB v1.0 (???? ?? / Sony)"
    ;;
  "a01041")
    INFO="Raspberry Pi 2 Model B [1GB] / PCB v1.1 (2015 Q1 / Sony)"
    ;;
  "a21041")
    INFO="Raspberry Pi 2 Model B [1GB] / PCB v1.1 (2015 Q1 / Embest)"
    ;;
  "a22042")
    INFO="Raspberry Pi 2 Model B (BCM2837) [1GB] / PCB v1.2 (2016 Q3 / Embest)"
    ;;
  "900021")
    INFO="Raspberry Pi 1 Model A+ [512MB] / PCB v1.1 (2016 Q3 / Sony)"
    ;;
  "900032")
    INFO="Raspberry Pi 1 Model B+ [512MB] / PCB v1.2 (2016 Q2 / Sony)"
    ;;
  "900092")
    INFO="Raspberry Pi Zero [512MB] / PCB v1.2 (2015 Q4 / Sony)"
    ;;
  "900093")
    INFO="Raspberry Pi Zero [512MB] / PCB v1.3 (2016 Q2 / Sony)"
    ;;
  "920093")
    INFO="Raspberry Pi Zero [512MB] / PCB v1.3 (2016 Q4 / Embest)"
    ;;
  "9000c1")
    INFO="Raspberry Pi Zero W [512MB] / PCB v1.1 (2017 Q1 / Sony)"
    ;;
  "a02082")
    INFO="Raspberry Pi 3 Model B [1GB] / PCB v1.2 (2016 Q1 / Sony)"
    ;;
  "a020a0")
    INFO="Compute Module [1GB] / PCB v1.0 (2017 Q1 / Sony)"
    ;;
  "a22082")
    INFO="Raspberry Pi 3 Model B [1GB] / PCB v1.2 (2016 Q1 / Embest)"
    ;;
  "a32082")
    INFO="Raspberry Pi 3 Model B [1GB] / PCB v1.2 (2016 Q4 / Sony Japan)"
    ;;
  "a32083")
    INFO="Raspberry Pi 3 Model B+ [1GB] / PCB v1.3 (2018 Q1 / Sony)"
    ;;
  *)
    INFO=""
    ;;
esac
echo ""
echo "${INFO}"

TEMP=$(cat /sys/class/thermal/thermal_zone0/temp)
CPUCLK=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)
ARMMEM=$(vcgencmd get_mem arm | sed -n 's|^arm=\(.*\)M|\1|p')
GPUMEM=$(vcgencmd get_mem gpu | sed -n 's|^gpu=\(.*\)M|\1|p')
LOAD=$(cat /proc/loadavg | awk -F ' ' '{print $1} {print $2} {print $3}')

TEMP1=$((TEMP / 1000))
TEMP2=$((TEMP % 1000))
CPUCLK1=$((CPUCLK / 1000))
CPUCLK2=$((CPUCLK % 1000))

echo ""
printf "CPU - Temp: %d.%.3d C / Clock: %d.%.3d MHz\n" ${TEMP1} ${TEMP2} ${CPUCLK1} ${CPUCLK2}
echo "RAM - Arm: ${ARMMEM} M / Gpu: ${GPUMEM} M"
echo Load: ${LOAD}
echo ""
echo "$(lsb_release -d | sed -n 's|^Description:\s*\(.*\)|\1|p')"
echo ""
